[model]
projectPath = d:\\Lessons\\Contributions\\2020\\Sudakov\\Project_3(218)\\Project3\\TEST_Reservoir_08152021

[layers]
layersSet = Ä0; Ä1à; Ä1á1; Ä1á2; Ä1á3; Ä1â; Ä1ã1; Ä1ã2+3; Ä1ä
groups = 1; 1; 3; 4

[numerical parmeters]
tol = 1E-2

[temporal parameters]
currentDate = 01.05.2020
startDate = 01.05.2020
endDate = 22.05.2021
snapshotNmbr = 61
timeStep = 5

[anomaly]
anomalyDetectionInterval = 7

[boundary_conditions]
initpressure = 16.7E1

[physicalConstants_SI]
g = 9.81
DENSITY_OF_OIL = 800
DENSITY_OF_WATER = 1000
VISCOSITY_OIL = 4.3
VISCOSITY_WATER = 2
COMPRESSIBILITY_OIL = 1E-3
COMPRESSIBILITY_WATER = 1E-4
PERMEABILITY = 500
POROSITY = 0.3
residualOil = 0.0
residualWater = 0.0

reference_pressure_for_compressibility = 1

[saveFileNames]
s_o = test_oil.txt
s_w = test_water.txt
p = test_pressure.txt
overallBalance = test_overallBalance.txt
doSave = 1